### PR TITLE
TypeConverter

### PR DESCRIPTION
**Pull request by rcollina**
Hi,
Unless I missed something (might as well be), there are issues using NUlid with Newtonsoft.JsonSerializer.

I managed to serialize to and deserialize from json by adding a TypeConverter. Tests included.

### CODE REVIEW

**Comment by RobThree** [comment]
Maybe we should also apply the `[Serializable]` attribute? I'm trying to get this (within reason) as close to a `Guid` as possible (see the [reference source](https://referencesource.microsoft.com/#mscorlib/system/guid.cs,b622ef5f6b76c10a)) in terms of implemented interfaces etc.

**Comment by RobThree** [comment]
Also: is the `UlidTypeConverter`'s accessibility  level deliberately `internal`? Shouldn't it be `public`?

**Comment by RobThree** [comment]
I've tried to handle more (de)serialization scenario's (WCF's `DataContract` method for example); I'm not sure I want to keep it this way (`XmlSerializer` and `DataContractSerializer` both don't quite output the desired results (e.g. simply the string representation)) but it'll do for now.

I've published 1.2 on NuGet (and mentioned your help in the version history of the helpfile).

**Comment by rcollina** [comment]
Sorry for not getting back to you sooner, and thank you for merging the PR!

The type converter is deliberately internal. TypeDescriptor seems to resolve it just fine, and, if I'm not mistaken, calling TypeDescriptor.GetConverter should be the preferred way of obtaining a TypeConverter.

I think I missed an IsValid TC overload.

Thanks for the mention in the helpfile :)

**Comment by rcollina** [comment]
On mobile right now, I'll have a look at Guid's ref source and see if I can improve here and there.

If I understand correctly, you'd like to see both the Time and Random part in the serialization output?

**Comment by RobThree** [comment]
> If I understand correctly, you'd like to see both the Time and Random part in the serialization output?

Actually, no. I'd like a ULID to have only one 'form' or representation: It's BASE32 representation (what `.ToString()` does). So it should be serialized to and from that form (in json/xml/whatever; binary or other non-human-readable forms are a different matter; they should probably be the actual byte-array).

> see if I can improve here and there

I already did some work (see 6c0c995b26f0e455fbf7132879f82a5b93f594e8)

**Comment by rcollina** [comment]
Understood. Thanks again for the merge :)

**Comment by symbiogenesis** [comment]
Looks like this same kind of fix is needed for System.Text.Json

```
System.NotSupportedException: The type 'NUlid.Ulid' is not a supported dictionary key using converter of type 'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[NUlid.Ulid]'. The unsupported member type is located on type 'Microsoft.Maui.Maps.MapSpan'. Path: $.CachedSearchMapSpans.
 ---> System.NotSupportedException: The type 'NUlid.Ulid' is not a supported dictionary key using converter of type 'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[NUlid.Ulid]'.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DictionaryKeyTypeNotSupported(Type keyType, JsonConverter converter)
```

**Pull request merged**
