### PR TITLE
.NET Core support

### PR DESCRIPTION
**Pull request by adamhathcock**
Using xproj and project.json.

I didn't port the performance package but can do.

### CODE REVIEW

**Comment by adamhathcock** [comment]
I didn't realize you were waiting for this build to pass :)

For appveyor I added a config file and reused some Cake stuff to build.

The solution opens but I don't know if I can fix the documentation project.  Still didn't port over the performance package.

If things are fine, you'll probably want to bump the version in the project.json

**Comment by adamhathcock** [comment]
Any chance to get this looked at?  I'm considering forking.

**Comment by RobThree** [comment]
> Any chance to get this looked at? I'm considering forking.

It will get looked at / be done. But as I just bought a new house and I'm busy moving etc. this might take a little while since I'm pretty short on spare time 😉

**Comment by adamhathcock** [comment]
No worries then.  Just didn't know if this was an active project or not.  I understand about real life stuff :)

**Comment by RobThree** [comment]
See 4878f942455631b1f6844163dca5bc34b6600471

Thanks for the effort though! 👍

**Pull request closed without merging**
